[package]
name = "bf_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getch = "0.3.1"
thiserror = "1.0.40"

[[bin]]
path = "src/main.rs"
name = "bf"